version: '3.3'
services:
    database:
        ports:
            - '5333:5332'
        environment:
            - POSTGRES_PASSWORD=1234
        image: 'postgres:12.2'
        restart: always


    webapp:
      build: .
      ports:
        - '80:5000'
      depends_on:
        - database
        - memcached
      restart: on-failure

    memcached:
      image: 'memcached'
      ports:
        - '11211:11211'
      restart: always