apiVersion: skaffold/v2alpha4
kind: Config

metadata:
  name: BigData

build:
  artifacts:
    # create an docker image named webapp from the Dockerfile in the "." directory
    - image: webapp
      context: .

    # - image: k8s/popular-slides-spark
    #   context: spark-app

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
