apiVersion: skaffold/v2alpha4
kind: Config

metadata:
  name: BigData

build:
  artifacts:
    # create an docker image named webapp from the Dockerfile in the "." directory
    - image: webapp
      context: .

    # - image: k8s/popular-slides-spark
    #   context: spark-app

deploy:
  # Helm is used to automate some steps of setting up the cluster ressources
  # helm CLI is in beta, so manual instructions will be included
  helm: 
    releases:
    - name: kafka-release
      remoteChart: bitnami/kafka
      namespace: legerible-kafka
      createNamespace: true
      # these steps can be done manually by running this:
      # helm install kafka-release bitnami/kafka --create-namespace -n legerible-kafka
      
  kubectl:
    manifests:
      - k8s/*.yaml
