apiVersion: skaffold/v2beta17
kind: Config

metadata:
  name: BigData

build:
  artifacts:
    # create an docker image named webapp from the Dockerfile in the "." directory
    - image: webapp
      context: .

    - image: spark-starter
      context: Spark/

deploy:
  # use helm to auto-create Spark server, workers, etc
  # you need to run this once manually before you run skaffold dev:
  # > helm repo add bitnami https://charts.bitnami.com/bitnami
  helm: 
    releases:
      - name: spark-release
        remoteChart: bitnami/spark # will automatically install the latest version of spark
        # repo cannot be referenced in this way for some reason
        # repo: https://charts.bitnami.com/bitnami # official bitnami repository
        namespace: legerible-spark
        createNamespace: true
        # To setup spark ressources manually run this (assuming you have helm and it is up-to-date):
        # > helm install --repo https://charts.bitnami.com/bitnami spark-release spark -n legerible-spark --create-namespace
        # pulls the newest helm chart before building
        upgradeOnChange: true
        
  kubectl:
    manifests:
      - k8s/*.yaml

portForward:
  # forward the spark master node GUI
  # You can access it on localhost:7077
  # You can see the spark worker nodes and the running application there
  - resourceType: Service
    resourceName: spark-release-master-svc
    namespace: legerible-spark
    port: 80
    localPort: 7077
