apiVersion: skaffold/v2alpha4
kind: Config

metadata:
  name: BigData

build:
  artifacts:
    - image: k8s/popular-slides
      context: web-app

    - image: k8s/popular-slides-spark
      context: spark-app

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
