#Begin: Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: memcached
  name: memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      service: memcached
  template:
    metadata:
      labels:
        service: memcached
    spec:
      containers:
        - image: memcached
          name: memcached
          ports:
            - containerPort: 11211
      restartPolicy: Always
#End: Deployment

---
#Begin: Service
apiVersion: v1
kind: Service
metadata:
  labels:
    service: memcached
  name: memcached
spec:
  ports:
    - port: 11211
      targetPort: 11211
  selector:
    service: memcached
#End: Service
