apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # Mount the configmap volume
      # This is an excerpt of deployment.spec.template.spec
      containers:
        - name: postgres
          image: 'postgres:12.2'
          # Set required environment variables to initialize the container
          env:
            - name: POSTGRES_PASSWORD
              value: "1234"
          ports:
            - containerPort: 5532

---
#Begin: Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - name: postgres-xproto
      protocol: TCP
      port: 5532
      targetPort: 5532
#End: Service
