#Begin: Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      service: database
  template:
    metadata:
      labels:
        service: database
    spec:
      containers:
        # environment variables used for postgres config
        - env:
            - name: POSTGRES_PASSWORD
              value: "1234"
          image: postgres:12.2
          name: database
          ports:
          # default port for postgres
            - containerPort: 5432 #previously 5332
      restartPolicy: Always
#End: Deployment

---
#Begin: Service
apiVersion: v1
kind: Service
metadata:
  labels:
    service: database
  name: database
spec:
  ports:
  # using default ports for postgres
    - port: 5432 #previously 5333
      targetPort: 5432 #previously 5332
  selector:
    service: database
#End: Service
