#Begin: Deployment (might be changed to deployment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-pod
  template:
    metadata:
      labels:
        app: webapp-pod
    spec:
      containers:
        - name: webapp-container
          image: webapp
          imagePullPolicy: Never
          name: webapp
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always

# End: Deployment

---
#Begin: Service
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp-pod
  ports:
    - port: 5000
      targetPort: 5000
      # nodePort: 30010 # access the node directly from the browser. range 30000 to 32767 Only for debugging
  type: LoadBalancer
  
#End: Service

---
#Begin: Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: legerible-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webapp
                port: 
                  number: 5000
#End: Ingress