#Begin: Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-bib
  labels:
    app: project-bib
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: web-app
          image: .
          ports:
            - containerPort: 5000

---
#Begin: Service
kind: Service
apiVersion: v1
metadata:
  name: web-service
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
#End: Service

---
#Begin: Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-bib-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: project-bib-service
                port:
                  number: 3000
