#Begin: Pod (might be changed to deployment)
apiVersion: v1
kind: Pod
metadata:
  labels:
    service: webapp
  name: webapp
spec:
  containers:
    - image: webapp
      name: webapp
      ports:
        - containerPort: 5000
  restartPolicy: OnFailure

# End: Pod

---
#Begin: Service
apiVersion: v1
kind: Service
metadata:
  labels:
    service: webapp
  name: webapp
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    service: webapp
#End: Service

---
#Begin: Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: legerible-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webapp
                port:
                  number: 80
#End: Ingress