# This file holds configuration information for the deployment 
# of the cassandra distributed database.
# It is created via a helm chart and references the 
# ConfigMap that is definied in k8s/start_cassandra
---
dbUser:
  user: "cassandra-legerible"
  password: "ChangeThis"

initDBConfigMap: init-cassandra

# try using the automatic replica count, it may be causing authentication problems
# See also: https://community.datastax.com/questions/5175/authenticationfailed-if-one-node-is-down.html
#replicaCount: 5